name: sline
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  image_picker: ^1.0.4
  supabase_flutter: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo kosmetik 2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/lipstick.webp
    - assets/images/blush.png
    - assets/images/mascara.png
    - assets/images/kosmetik.png
    - assets/images/logo kosmetik 2.png
